formularios_homepage:
    path:     /
    defaults: { _controller: FormulariosBundle:Formulario:index }
    
formularios_nuevo:
    path:     /nuevo
    defaults: { _controller: FormulariosBundle:Formulario:nuevo }
    
formularios_crear:
    path:     /crear
    defaults: { _controller: FormulariosBundle:Formulario:crear }
    
formularios_editar:
    path:     /editar/{id}
    defaults: { _controller: FormulariosBundle:Formulario:editar }
    
formularios_actualizar:
    path:     /actualizar/{id}
    defaults: { _controller: FormulariosBundle:Formulario:actualizar }
